### ISSUE TITLE
Running FFE

### ISSUE THREAD

**Issue by trans** [tonyrog/ffe#2]
So I am not sure how to run the examples, or play around with ffe in general. My first guess at this is `priv/ffs.sh`. I assume that would perhaps give me a repl? So I tried it and got the following:

    > ./priv/ffe.sh 
    {"init terminating in do_boot",{undef,[{ffe,start,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
    init terminating in do_boot ({undef,[{ffe,start,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})
    Crash dump is being written to: erl_crash.dump...done

What should I be doing to get started?

**Comment by tonyrog** [comment]
I usually set the environment variable ERL_LIBS to point my active libraries and applications,
but you can locally alter the script start with -pa <path-to-ffe-ebin-including-the-parent-directory>
Important things are the -noinput and -noshell variants to make sure an erlang shell is not started.
