### ISSUE TITLE
binary_to_atom

### ISSUE THREAD

**Issue by skvamme** [tonyrog/ffe#3]
Hi :)
Compiled on my raspberry pi and had to change
binary_to_atom/1 to binary_to_atom/2

Erlang/OTP 22

Still problems in ffe.sh to get it running.

Best regards
skvamme

**Comment by tonyrog** [comment]
Hi!
Make sense binary_to_atom/1 was introduced in OTP 23.0.
binary_to_atom(Bin) == binary_to_atom(Bin, utf8)
I will update this to make it easy.

When it come to starting. Have you set ERL_LIBS ? or have you added path (-pa path-to-ffe) ?

**Comment by skvamme** [comment]
./priv/ffe.sh -pa ./ebin
Starts and run fine, thanks!
